### ISSUE TITLE
Is it possible to rename a space?

### ISSUE THREAD

**Issue by lol768** [Tablane/tablane#13]
![Screenshot from 2023-01-06 21-03-57](https://user-images.githubusercontent.com/2552726/211099767-13ce18b2-c932-4fb8-9ec6-dd189f7d89c9.png)

Maybe clicking the pencil icon is not implemented yet?

**Comment by MarconLP** [comment]
Try to reload the page and try again.

There was a bug that the Home button was stealing the focus.

**Comment by lol768** [comment]
Much better, thanks
