### ISSUE TITLE
Idea: automatically pick light coloured label text if label BG is too dark to pass WCAG AA contrast test

### ISSUE THREAD

**Issue by lol768** [Tablane/tablane#14]
![image](https://user-images.githubusercontent.com/2552726/211100738-d4643258-9ae7-4958-83a3-7650b92ed0a4.png)

Consider e.g. https://stackoverflow.com/a/49092130/5056459

**Comment by MarconLP** [comment]
@lol768 Thanks for that stackOverflow post!
