### ISSUE TITLE
Task Status Menu Rendering Issue: 

### ISSUE THREAD

**Issue by mjrochford** [Tablane/tablane#16]
Example:
![image](https://user-images.githubusercontent.com/33612715/211126077-708a9f34-5342-4ba9-8acd-08a95c9b0d9e.png)
[tablane url](https://app.tablane.net/shared/board/63b8d00aa6daae26e3db2a43)

Description:
The menu for changing statuses incorrectly renders when grouped by statuses

**Comment by MarconLP** [comment]
@mjrochford Thanks for reporting this issue!
