### ISSUE TITLE
plus emails do not pass validation (example: contact+me@tablane.net)

### ISSUE THREAD

**Issue by MarconLP** [Tablane/tablane#17]
context: https://news.ycombinator.com/item?id=34286915

**Comment by ayakovlenko** [comment]
You can use: https://emailregex.com/

If I recall correctly it won't handle mixed case, so make sure to use `i` modifier for the regex.

**Comment by MarconLP** [comment]
@ayakovlenko Seems to work without the `i` modifier
![grafik](https://user-images.githubusercontent.com/13001502/211213520-0f20bb9e-b0ea-49b5-a8e9-b1dacab5bfab.png)
